### ISSUE TITLE
Wish: pause, seek, volume

### ISSUE THREAD

**Issue by praharshbhatt** [fireslime/flutter_gapless_audio_loop#1]
Request to add pause/resume, seek and volume methods.
Thanks.

**Comment by praharshbhatt** [comment]
Hello there!
Any advancements on this?

**Comment by erickzanardo** [comment]
I am going to try working on this this week, haven't had much time yet.

**Comment by erickzanardo** [comment]
- [x] Pause/Resume https://github.com/fireslime/flutter_gapless_audio_loop/commit/f79845b4555f5241b0c0f86c63d10047e5d323b1
- [x] Volume
  - [x] Android https://github.com/fireslime/flutter_gapless_audio_loop/commit/268ba3037c1effca5bd95b0d1ac740bd28bb6fdd
  - [x] iOS https://github.com/fireslime/flutter_gapless_audio_loop/commit/fef649a8323625db8fa1c32a9c52263d1a1e16c3
- [x] Seek https://github.com/fireslime/flutter_gapless_audio_loop/commit/acac714a87a0a9ed00888b0108dbbf7bf5f4efa4

**Comment by erickzanardo** [comment]
I am not sure about the seek feature, specially on Android, where we need to use multiple MediaPlayers to create the gapless effect, if you seek more than the current player has yet left to play, it would be kind difficult to calculate it. Is the seek feature something really needed for you?

**Comment by praharshbhatt** [comment]
We really do need the seek function.
Can you give it a shot?

**Comment by erickzanardo** [comment]
The only manageable way to this in my head right now is doing the following:

seek will receive a duration, that duration must be between the duration of the original file, like if the if the file has 30 seconds, you can only seek between 0 or 30.

With this constraints I don't have to worry about someone calling the seek with a duration bigger than the current iteration of the loop.

Sounds good to you?

**Comment by praharshbhatt** [comment]
> The only manageable way to this in my head right now is doing the following:
> seek will receive a duration, that duration must be between the duration of the original file, like if the if the file has 30 seconds, you can only seek between 0 or 30.


Yes. this solves the problem.

**Comment by erickzanardo** [comment]
Okay, will do that when I find some more time. Thanks for the reply.

**Comment by erickzanardo** [comment]
Done on `1.0.0`
