### ISSUE TITLE
Cannot compile pub.dev package

### ISSUE THREAD

**Issue by alanmeier** [fireslime/flutter_gapless_audio_loop#10]
Hi there,

It seems that the pub.dev package is out of step with the changes on the master. I tried manually adding the package but it still fails. Could someone please upgrade the pub.dev version so it now compiles as at present it gets a compile error that has already been fixed in the master but has not yet been moved to pub.dev

https://github.com/fireslime/flutter_gapless_audio_loop/commit/ff1b2ab0a6c773a7db5213618d6330de1350c7e7

Look forward to using it in my app.

Thanks
Alan

**Comment by erickzanardo** [comment]
Hey, I just uploaded the `1.1.1` to pub.

But be aware that this package is no longer maintained, I have create a [new package](https://github.com/erickzanardo/ocarina) to support gapless loop

**Comment by alanmeier** [comment]
Thanks very much I will check that out as well
