### ISSUE TITLE
Add ability to select different channel

### ISSUE THREAD

**Issue by FabulousGee** [fireslime/flutter_gapless_audio_loop#3]
Hey,

thanks for the great plugin - it's really useful though it's pretty simple (that's a plus!).

I just came across the wish that I wanted to select the channel to play the sound through. So I searched for an easy way to achieve this. You may also want to add a similar option to iOS-side.
Sorry for not raising a pull-request but I just hardcoded the alarm-channel for me to keep the overhead on a minimum.

For android it was pretty simple
```
import android.media.AudioAttributes;
import android.media.AudioManager;

class GaplessPlayer {
    ...
    GaplessPlayer(String url, double volume) {
        ...
            currentPlayer.setVolume((float) volume, (float) volume);

            if (android.os.Build.VERSION.SDK_INT >= 21) {
                currentPlayer.setAudioAttributes(new AudioAttributes.Builder()
                        .setUsage(AudioAttributes.USAGE_ALARM)
                        .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                        .build());
            } else {
                currentPlayer.setAudioStreamType(AudioManager.STREAM_ALARM);
            }

            currentPlayer.setOnPreparedListener(new MediaPlayer.OnPreparedListener() {
            ...
```

Keep it going, appreciate your work!

**Comment by erickzanardo** [comment]
This package is no longer maintained, I have create a [new package](https://github.com/erickzanardo/ocarina) to support gapless loop
