### ISSUE TITLE
How do I stop GaplessAudioLoop on app restart (Flutter)?

### ISSUE THREAD

**Issue by nohli** [fireslime/flutter_gapless_audio_loop#8]
First, thanks for the great plugin! It loops really well and unnoticeable.

When using the simulator and performing a hot restart, the audio won't stop playing until the app is completely shut down through swiping in the app switcher.

Is there a way to stop all audio, even when the GaplessAudioLoop instance is gone?

Also (another question), after pausing/ stopping one instance of GaplessAudioLoop, it won't .play() any more, so I have to create a new instance every time I want to start playing a loop, is that correct?
(in audioplayers I use one instance for everything)

**Comment by erickzanardo** [comment]
> The audio won't stop playing, until the app is completely shut down through swiping in the app switcher.
Yeah, that is a problem that happens on audioplayers as well if I recall correctly, audio won't stop when hot reloading.

>so I have to create a new instance every time I want to start playing a loop, is that correct?

This is weird, you should be able to re use instances, on our last project using this package we re used the instances and it worked, maybe this is a new bug?

**Comment by nohli** [comment]
Yes, you're correct, audioplayers also continues to play audio. So I guess, I'm going to close this issue as there is no foreseeable fix.

The not working (at least for me on flutter beta channel) re-use of instances is not a problem, already made a workaround for being able to stop audio (Idk if it is elegant or not):

```
Future<void> pause(int milliseconds) =>
    Future.delayed(Duration(milliseconds: milliseconds));

bool _loopPlaying = false;

Future<void> soundLoop(String _sound) async {
  if (_sound != '') {
    await stopLoopAudio();
    GaplessAudioLoop _loopPlayer = GaplessAudioLoop();
    _loopPlayer.setVolume(_sound == silence ? 0 : volume / 2);
    await _loopPlayer.loadAsset('sounds/ambient/' + _sound);
    if (_loopPlayer.isAssetLoaded()) {
      _loopPlaying = true;
      await _loopPlayer.play();
      while (_loopPlaying) await pause(5);
      _loopPlayer.stop();
    }
  }
}

Future<void> stopLoopAudio() async {
  _loopPlaying = false;
  await pause(5);
}
```

Btw. (if you've noticed the line) ` loopPlayer.setVolume(sound == silence ? 0 : volume / 2);`
...I found out that if a (silent) GaplessAudioLoop is running, the audio of audioplayers would keep working on iOS even when the app is in background :)
